global using FotoStorio.Server.Contracts;
global using FotoStorio.Server.Helpers;
global using FotoStorio.Shared.DTOs;
global using FotoStorio.Shared.Models;
global using Xunit;
global using FluentAssertions;
global using NSubstitute;
global using NSubstitute.ReturnsExtensions;
global using AutoFixture;
